pni-libraries/python-pninexus

test/regression_tests/__init__.py, test/regression_tests/issue_5.py
=> Issue is solved

MANIFEST.in
build_tools should be added to sources
=> add build_tools

MANIFEST.in
exclude .gitignore from sources
=> exclude .gitignore

MANIFEST.in
exclude sphinx .gitignore from sources
=> exclude sphinx .gitignore

MANIFEST.in
exclude all .gitignore from sources
=> exclude all .gitignore from sources

src/cpp/h5cpp/dimensions_conversion.hpp
it fixes https://github.com/pni-libraries/python-pni/issues/41
=> add stl_iteralor include statement to fix jessie error

test/h5cpp_tests/node_tests/h5py_compat_test.py
fix https://github.com/pni-libraries/python-pni/issues/45 and https://github.com/pni-libraries/python-pni/issues/44
=> fix tests for H5pyCompatibilityReading

src/pninexus/h5cpp/node/__init__.py, src/pninexus/nexus/__init__.py
=> fix None comparison

src/cpp/h5cpp/numpy/hdf5_variable_strings_support.hpp
=> fix seg fault by providing an empty string

src/cpp/h5cpp/node/nodes.cpp
=> adding missing interface Group::[get/has]_[group/dataset]

src/pninexus/h5cpp/datatype/__init__.py
It is workaround for parts of the problems related to #64
=> add workaround for missing bool

.travis.yml, .travis/debian10_py2/Dockerfile, .travis/debian10_py3/Dockerfile, .travis/debian9_py2/Dockerfile, .travis/debian9_py3/Dockerfile, .travis/ubuntu18.04_py2/Dockerfile, .travis/ubuntu18.04_py3/Dockerfile, .travis/ubuntu18.10_py2/Dockerfile, .travis/ubuntu18.10_py3/Dockerfile, src/cpp/h5cpp/filter/filter.cpp, src/pninexus/h5cpp/filter/__init__.py, test/h5cpp_tests/filter_tests/creation_test.py
it allows to use external filters without defining a new class.
=> add ExternalFilter class

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/debian9_py2/Dockerfile, .ci/debian9_py3/Dockerfile, .ci/ubuntu18.04_py2/Dockerfile, .ci/ubuntu18.04_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu20.10_py3/Dockerfile, .github/workflows/tests.yml, pkgconfig.py, setup.py, src/cpp/h5cpp/file/file.cpp, src/pninexus/h5cpp/file/__init__.py, test/h5cpp_tests/__init__.py, test/h5cpp_tests/file_image.py
It resolves #97 by adding a wrapper for `File::to_buffer()` and `from_buffer()` functions.
=> Issue 97: add support for image file buffer

src/cpp/h5cpp/datatype/datatype.cpp, test/h5cpp_tests/datatype_tests/predefined_type_tests.py
It resolves #93 by adding float properties: precision, offset, order, pad, inpad, norm, ebias, fields.
=> Issue 93: add float properties

src/cpp/h5cpp/filter/filter.cpp, src/cpp/h5cpp/property/class_wrappers.cpp, test/h5cpp_tests/filter_tests/creation_test.py
it resolves #98 by adding `Filter.is_encoding_enabled()`, `Filter.is_decoding_enabled()` and `DatasetCreationList.nfilters`
=> Issue 98: add is_encoding_enabled, is_decoding_enabled and nfilters

src/cpp/h5cpp/filter/filter.cpp, src/pninexus/h5cpp/filter/__init__.py, src/pninexus/h5cpp/node/__init__.py, test/h5cpp_tests/filter_tests/creation_test.py, test/h5cpp_tests/node_tests/dataset_direct_chunk_test.py
It resolves #96 by adding wrapper for ExternalFilters class and related methods.
=> Issue 96: add ExternalFilters 

src/cpp/h5cpp/filter/filter.cpp, src/pninexus/h5cpp/filter/__init__.py, test/h5cpp_tests/filter_tests/creation_test.py
It resolves #95 by adding NBit SZip and ScaleOffset filter wrappers
=> add NBit SZip and ScaleOffset filters

src/cpp/h5cpp/datatype/datatype.cpp, src/pninexus/h5cpp/datatype/__init__.py, test/h5cpp_tests/datatype_tests/predefined_type_tests.py, test/h5cpp_tests/node_tests/dataset_io_test.py
It resolves #92 by adding a wrapper for the float16 type
=> Issue 92: add a wrapper for float16 type

.ci/install.sh, doc/sphinx/conf.py, doc/sphinx/h5cpp/dataspace.rst, doc/sphinx/h5cpp/datatype.rst
It adds doc building to tests and resolves #108
=> Issue 108: add doc building to tests

doc/sphinx/h5cpp/node.rst
It resolves #110 by adding :noindex: for Dataset.read in h5cpp/node.rst
=> Issue 110: add :noindex:

doc/sphinx/conf.py
it resolves #116 by adding the PNINEXUS_MATH_EXT switch
=> Issue 116: add the PNINEXUS_MATH_EXT switch

setup.py, src/pninexus/h5cpp/file/__init__.py, test/h5cpp_tests/file_image.py
it resolves #124 by adding missing ImageFlags wrapper and bump the version to v1.3.2
=> Issue_124: Add ImageFlags wrapper and bump the version

.ci/debian11_py3/Dockerfile, src/cpp/h5cpp/property/class_wrappers.cpp, test/h5cpp_tests/node_tests/virtual_dataset_test.py
It resolves #126 by adding `DatasetCreationList.set_fill_value(v, dt)` and `DatasetCreationList.fill_value(dt)` for VDS datasets.
=> Issue 126: add fill_value methods

setup.py
It resolves #128 by bumping the version
=> Issue 128: bump the version

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/debian9_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu21.04_py3/Dockerfile, .github/workflows/tests.yml
It resolves #135 by adding ubuntu 21.04 tests
=> Issue 135: add ubuntu 21.04 tests and update tests

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/debian9_py2/Dockerfile, .ci/debian9_py3/Dockerfile, .ci/ubuntu18.04_py2/Dockerfile, .ci/ubuntu18.04_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu21.04_py3/Dockerfile
=> Issue 137: remove ENV HDF5_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/hdf5/plugins

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/ubuntu21.04_py3/Dockerfile, .ci/ubuntu21.10_py3/Dockerfile, .github/workflows/tests.yml, README.md, doc/sphinx/installation.rst
It resolves #145 by update tests and documentation
=> Issue 145: replace apt-key command in documentation

README.md, src/cpp/h5cpp/_h5cpp.cpp, src/cpp/h5cpp/attribute/attribute.cpp, src/cpp/h5cpp/common/converters.hpp, src/cpp/h5cpp/common/io.hpp, src/cpp/h5cpp/dataspace/dataspace.cpp, src/cpp/h5cpp/dataspace/selections.cpp, src/cpp/h5cpp/datatype/datatype.cpp, src/cpp/h5cpp/dimensions_conversion.hpp, src/cpp/h5cpp/file/file.cpp, src/cpp/h5cpp/filter/filter.cpp, src/cpp/h5cpp/iterator_wrapper.hpp, src/cpp/h5cpp/node/dataset.cpp, src/cpp/h5cpp/node/functions.cpp, src/cpp/h5cpp/node/nodes.cpp, src/cpp/h5cpp/numpy/array_adapter.hpp, src/cpp/h5cpp/numpy/array_factory.cpp, src/cpp/h5cpp/numpy/array_factory.hpp, src/cpp/h5cpp/numpy/dimensions.hpp, src/cpp/h5cpp/numpy/hdf5_fixed_strings_support.hpp, src/cpp/h5cpp/numpy/hdf5_support.hpp, src/cpp/h5cpp/property/chunk_cache_parameters.cpp, src/cpp/h5cpp/property/class_wrappers.cpp, src/cpp/h5cpp/property/copy_flag_wrapper.cpp, src/cpp/h5cpp/property/creation_order.cpp, src/cpp/h5cpp/property/enumeration_wrappers.cpp, src/cpp/h5cpp/property/property.cpp, src/cpp/nexus/factories.cpp, src/cpp/nexus/nexus.cpp, src/cpp/nexus/predicates.cpp
It resolves #158 by adding #include <h5cpp/contrib/stl/stl.hpp> statements
=> Issue 158: add #include <h5cpp/contrib/stl/stl.hpp> statements

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu21.10_py3/Dockerfile, src/cpp/h5cpp/dataspace/selections.cpp, src/pninexus/h5cpp/dataspace/__init__.py, src/pninexus/h5cpp/node/__init__.py, test/h5cpp_tests/node_tests/dataset_partial_io_test.py
It resolves #161 by adding H5CPP prefix
=> Issue 161: add H5CPP_ prefix

.ci/ubuntu22.04_py3/Dockerfile, .github/workflows/tests.yml, README.md
It resolves #163 by replacing  ubuntu 21.10 tests to 22.04
=> update tests to jammy

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/debian9_py2/Dockerfile, .ci/debian9_py3/Dockerfile, .ci/ubuntu18.04_py2/Dockerfile, .ci/ubuntu18.04_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu22.04_py3/Dockerfile, MANIFEST.in, doc/sphinx/conf.py, setup.py
It bumps the version to v3.0.1
=> Issue 169: Release 3.0.1

.ci/ubuntu22.10_py3/Dockerfile, .github/workflows/tests.yml
It resolves #171 by adding ubuntu20.10 tests
=> Issue 171: add ubuntu20.10 tests

.ci/debian10_py2/Dockerfile, .ci/debian10_py3/Dockerfile, .ci/debian11_py3/Dockerfile, .ci/debian9_py2/Dockerfile, .ci/debian9_py3/Dockerfile, .ci/ubuntu18.04_py2/Dockerfile, .ci/ubuntu18.04_py3/Dockerfile, .ci/ubuntu20.04_py3/Dockerfile, .ci/ubuntu22.04_py3/Dockerfile, .ci/ubuntu22.10_py3/Dockerfile, doc/sphinx/conf.py, doc/sphinx/installation.rst, setup.py
=> Issue 173: Release 3.0.2
